services:
  rabbitmq:
    image: 'rabbitmq:3.13.3-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=admin'
      - 'RABBITMQ_DEFAULT_USER=admin'
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'

  order-service:
    build:
      context: order-service
    ports:
      - '8080:8080'
    depends_on:
      - rabbitmq

  stock-service:
    build:
      context: stock-service
    ports:
      - '8081:8080'
    depends_on:
      - rabbitmq
      - order-service

  email-service:
    build:
      context: email-service
    ports:
      - '8082:8080'
    depends_on:
      - rabbitmq
      - order-service
